services:
  mongo:
    image: mongo:8.0.1
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    command: ["--replSet", "my-replica-set", "--bind_ip_all"]
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"localhost:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
