import { BlockchainNode } from ".";

export const dataXX: BlockchainNode[] = [
  {
    id: "1",
    name: "Ethereum",
    nodesActive: 10,
    nodesInactive: 10,
    requests: {
      total: 8945600,
      perSecond: 15233,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Sepolia RPC"],
    testnetEndpoints: ["Sepolia WS RPC", "Beacon API"],
  },
  {
    id: "2",
    name: "Bitcoin",
    nodesActive: 15,
    nodesInactive: 5,
    requests: {
      total: 7845900,
      perSecond: 12500,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Bitcoin Core"],
    testnetEndpoints: ["Testnet RPC", "Lightning API"],
  },
  {
    id: "3",
    name: "Polygon",
    nodesActive: 8,
    nodesInactive: 12,
    requests: {
      total: 5632100,
      perSecond: 9876,
    },
    hardFork: "Mumbai",
    mainnetEndpoints: ["RPC", "Matic API"],
    testnetEndpoints: ["Mumbai Testnet", "WS API"],
  },
  {
    id: "4",
    name: "Solana",
    nodesActive: 12,
    nodesInactive: 8,
    requests: {
      total: 4521000,
      perSecond: 8765,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Solana API"],
    testnetEndpoints: ["Devnet", "Testnet API"],
  },
  {
    id: "5",
    name: "Cardano",
    nodesActive: 9,
    nodesInactive: 11,
    requests: {
      total: 3654200,
      perSecond: 7654,
    },
    hardFork: "Vasil",
    mainnetEndpoints: ["RPC", "Cardano API"],
    testnetEndpoints: ["Preview", "PreProd"],
  },
  {
    id: "6",
    name: "Avalanche",
    nodesActive: 11,
    nodesInactive: 9,
    requests: {
      total: 2987600,
      perSecond: 6543,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Avalanche API"],
    testnetEndpoints: ["Fuji", "Local Network"],
  },
  {
    id: "7",
    name: "Binance Smart Chain",
    nodesActive: 14,
    nodesInactive: 6,
    requests: {
      total: 6543200,
      perSecond: 11234,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "BSC API"],
    testnetEndpoints: ["Chapel", "Test API"],
  },
  {
    id: "8",
    name: "Polkadot",
    nodesActive: 7,
    nodesInactive: 13,
    requests: {
      total: 2345600,
      perSecond: 5432,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Polkadot API"],
    testnetEndpoints: ["Westend", "Rococo"],
  },
  {
    id: "9",
    name: "Cosmos",
    nodesActive: 13,
    nodesInactive: 7,
    requests: {
      total: 1987400,
      perSecond: 4321,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Cosmos API"],
    testnetEndpoints: ["Test Hub", "Dev API"],
  },
  {
    id: "10",
    name: "Near Protocol",
    nodesActive: 6,
    nodesInactive: 14,
    requests: {
      total: 1654300,
      perSecond: 3214,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Near API"],
    testnetEndpoints: ["Testnet", "Betanet"],
  },
  {
    id: "11",
    name: "Fantom",
    nodesActive: 16,
    nodesInactive: 4,
    requests: {
      total: 1432100,
      perSecond: 2987,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Fantom API"],
    testnetEndpoints: ["Testnet", "Opera API"],
  },
  {
    id: "12",
    name: "Algorand",
    nodesActive: 5,
    nodesInactive: 15,
    requests: {
      total: 1234500,
      perSecond: 2765,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Algo API"],
    testnetEndpoints: ["Testnet", "Betanet"],
  },
  {
    id: "13",
    name: "Tezos",
    nodesActive: 12,
    nodesInactive: 8,
    requests: {
      total: 987600,
      perSecond: 1876,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Tezos API"],
    testnetEndpoints: ["Ghostnet", "Mondaynet"],
  },
  {
    id: "14",
    name: "Harmony",
    nodesActive: 8,
    nodesInactive: 12,
    requests: {
      total: 876500,
      perSecond: 1654,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Harmony API"],
    testnetEndpoints: ["Testnet", "Devnet"],
  },
  {
    id: "15",
    name: "Elrond",
    nodesActive: 11,
    nodesInactive: 9,
    requests: {
      total: 765400,
      perSecond: 1432,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Elrond API"],
    testnetEndpoints: ["Testnet", "Devnet"],
  },
  {
    id: "16",
    name: "IOTA",
    nodesActive: 9,
    nodesInactive: 11,
    requests: {
      total: 654300,
      perSecond: 1234,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "IOTA API"],
    testnetEndpoints: ["Devnet", "EVM Testnet"],
  },
  {
    id: "17",
    name: "VeChain",
    nodesActive: 7,
    nodesInactive: 13,
    requests: {
      total: 543200,
      perSecond: 987,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "VeChain API"],
    testnetEndpoints: ["Testnet", "Development"],
  },
  {
    id: "18",
    name: "Hedera",
    nodesActive: 14,
    nodesInactive: 6,
    requests: {
      total: 432100,
      perSecond: 876,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Hedera API"],
    testnetEndpoints: ["Testnet", "Previewnet"],
  },
  {
    id: "19",
    name: "Flow",
    nodesActive: 10,
    nodesInactive: 10,
    requests: {
      total: 321000,
      perSecond: 765,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Flow API"],
    testnetEndpoints: ["Testnet", "Emulator"],
  },
  {
    id: "20",
    name: "Stellar",
    nodesActive: 13,
    nodesInactive: 7,
    requests: {
      total: 210000,
      perSecond: 654,
    },
    hardFork: "—",
    mainnetEndpoints: ["RPC", "Horizon API"],
    testnetEndpoints: ["Testnet", "Laboratory"],
  },
];
